/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2017-04-02 14:20:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.apache.commons.lang.StringEscapeUtils;
import br.com.forecast.cidade.servlet.HTMLEntities;
import br.com.forecast.jdbc.modelo.Cidade;

public final class adiciona_002dcidade_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Forecast</title>\r\n");
      out.write("</head>\r\n");

List<Cidade> cidades = (List<Cidade>)session.getAttribute("cidades");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("    <h1>Adiciona Cidades</h1>\r\n");
      out.write("    <hr />\r\n");
      out.write("    <form action=\"adicionaCidade\" method=\"POST\">\r\n");
      out.write("      Nome: <input type=\"text\" name=\"nome\" /><br />\r\n");
      out.write("      UF: <input type=\"text\" name=\"uf\" /><br />\r\n");
      out.write("      País: <input type=\"text\" name=\"pais\" /><br />\r\n");
      out.write("      \r\n");
      out.write("      <input type=\"submit\" value=\"Gravar\" />\r\n");
      out.write("    </form>\r\n");
      out.write("    <table>\r\n");
      out.write("      <tr>\r\n");
      out.write("\t\t<td>Cidade</td>\r\n");
      out.write("\t\t<td>Estado</td>\r\n");
      out.write("\t\t<td>País</td>\r\n");
      out.write("\t  </tr><tr></tr>\r\n");
      out.write("      ");

if(cidades!=null) {
      for (Cidade cidade : cidades ) {
      
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>");
      out.print(cidade.getNome() );
      out.write("</td> \r\n");
      out.write("          <td>");
      out.print(cidade.getUf() );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print(cidade.getPais() );
      out.write("</td>\r\n");
      out.write("          <td><a href=\"previsao.html?cidade=");
      out.print(HTMLEntities.htmlentities(cidade.getNome()));
      out.write("\">Tempo</a></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      ");

      }
}
      
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
